### ISSUE TITLE
[Ask] CMS

### ISSUE THREAD

**Issue by ridhof** [nathanael79/simple-js-cms#1]
bakal bikin CMS yang kayak gimana nih?
kebetulan lagi mau belajar strapi juga, nanti aku nyoba2 CMS mu ya mas bro

**Comment by nathanael79** [comment]
Hi @ridhof , ini masih backend mas bro, aku biasa pake backend dan frontend jadi satu di laravel. Ini aku mau misah keduanya, backend pake express js dan frontend pake vuejs. Let's discuss it via DM twitter, shall we?

**Comment by ridhof** [comment]
nice pake express sama vue, kebetulan lagi main keduanya juga.
wah jadi terpaksa buka twitter lagi ... baiklah nanti aku japri di DM ya @nathanael79

**Comment by nathanael79** [comment]
@ridhof oops so sorry, in what social media you want to use it?
